categories:
  - name: "学术与搜索"
    subcategories:
      - name: "学术文献"
        links:
          - title: "Google Scholar"
            url: "https://scholar.google.com/"
            description: "全球学术资源的搜索引擎。"
            logo: "images/favicons/Google Scholar.ico"
          - title: "PubMed"
            url: "https://pubmed.ncbi.nlm.nih.gov/"
            description: "生物医学领域的文献数据库。"
            logo: "images/favicons/PubMed.ico"
          - title: "arXiv"
            url: "https://arxiv.org/"
            description: "开放获取的学术论文预印本平台。"
            logo: "images/favicons/arXiv.ico"
          - title: "ResearchGate"
            url: "https://www.researchgate.net/"
            description: "科研人员的社交网络与文献分享平台。"
            logo: "images/favicons/ResearchGate.ico"
      - name: "代码托管"
        links:
          - title: "GitHub"
            url: "https://github.com/"
            description: "全球最大的代码托管平台。"
            logo: "images/favicons/GitHub.ico"
          - title: "Gitee"
            url: "https://gitee.com/"
            description: "国内知名的代码托管平台。"
            logo: "images/favicons/Gitee.ico"
          - title: "GitLab"
            url: "https://about.gitlab.com/"
            description: "提供代码托管、CI/CD和DevOps工具的一体化平台。"
            logo: "images/favicons/GitLab.ico"
      - name: "编程学习"
        links:
          - title: "菜鸟教学"
            url: "https://www.runoob.com/"
            description: "多语言，内容丰富的编程教学网站。"
            logo: "images/favicons/菜鸟教学.ico"
          - title: "w3School"
            url: "https://www.w3school.com.cn/"
            description: "经典编程学习网站。"
            logo: "images/favicons/w3School编程教学.ico"
      - name: "在线工具箱"
        links:
          - title: "JSON Formatter"
            url: "https://jsonformatter.curiousconcept.com/"
            description: "在线JSON格式化工具。"
            logo: "images/favicons/JSON Formatter.ico"
          - title: "Regex101"
            url: "https://regex101.com/"
            description: "在线正则表达式测试工具。"
            logo: "images/favicons/Regex101.ico"
          - title: "Smallpdf"
            url: "https://smallpdf.com/"
            description: "多功能PDF工具箱。"
            logo: "images/favicons/Smallpdf.ico"

  - name: "AI与开发"
    subcategories:
      - name: "文本生成"
        links:
          - title: "ChatGPT"
            url: "https://chatgpt.com/"
            description: "OpenAI 的智能对话平台。"
            logo: "images/favicons/ChatGPT.ico"
          - title: "Kimi AI助手"
            url: "https://kimi.moonshot.cn/"
            description: "Kimi AI助手，支持生成PPT。"
            logo: "images/favicons/Kimi AI助手.ico"
          - title: "DeepSeek"
            url: "https://www.deepseek.com/"
            description: "探索人工智能的无限可能。"
            logo: "images/favicons/DeepSeek.ico"
      - name: "AI开发项目"
        links:
          - title: "江湖笔者脚本"
            url: "https://github.com/qinyuanchun03/linux-tool-test"
            description: "AI相关脚本集合。"
      - name: "开发工具"
        links:
          - title: "Visual Studio Code"
            url: "https://code.visualstudio.com/"
            description: "微软开发的免费代码编辑器。"
            logo: "images/favicons/Visual Studio Code (VSCode).ico"
          - title: "Typora"
            url: "https://typora.io/"
            description: "简洁优雅的Markdown编辑器。"
            logo: "images/favicons/Typora.ico"
          - title: "Obsidian"
            url: "https://obsidian.md/"
            description: "基于Markdown的笔记工具。"
            logo: "images/favicons/Obsidian.ico"

  - name: "办公与效率"
    subcategories:
      - name: "云服务器"
        links:
          - title: "腾讯云"
            url: "https://cloud.tencent.com/"
            description: "提供稳定、安全、高效的云服务。"
            logo: "images/favicons/腾讯云.ico"
          - title: "华为云"
            url: "https://www.huaweicloud.com/"
            description: "全球领先的云计算服务提供商。"
            logo: "images/favicons/华为云.ico"
          - title: "Vultr"
            url: "https://www.vultr.com/"
            description: "高性能云服务器，支持按小时计费。"
            logo: "images/favicons/Vultr.ico"
      - name: "办公工具"
        links:
          - title: "WPS聚合分享"
            url: "https://www.123684.com/s/AJ3VVv-MrcBd"
            description: "仅支持Win用户，国产系统和Linux用户请不要下载。"
            logo: "images/favicons/WPS聚合分享.ico"
          - title: "OfficeToolPlus部署工具"
            url: "https://otp.landian.vip/zh-cn/"
            description: "免费的office安装激活工具。"
            logo: "images/favicons/OfficeToolPlus部署工具.ico"
      - name: "模板资源"
        links:
          - title: "第一ppt免费模板素材"
            url: "https://www.1ppt.com/"
            description: "免费ppt模板下载站。"
            logo: "images/favicons/第一ppt免费模板素材.ico"
          - title: "OfficePlus"
            url: "https://www.officeplus.cn/"
            description: "微软官方模板库。"
            logo: "images/favicons/OfficePlus.ico"

  - name: "网络与安全"
    subcategories:
      - name: "网络工具"
        links:
          - title: "ITDOG"
            url: "https://www.itdog.cn/"
            description: "提供网络监控、Ping测试、路由追踪等工具。"
            logo: "images/favicons/ITDOG.ico"
          - title: "WhatIsMyIP"
            url: "https://www.whatismyip.com/"
            description: "快速查询您的公网IP地址和网络信息。"
            logo: "images/favicons/WhatIsMyIP.ico"
          - title: "ip.sb"
            url: "https://ip.sb/"
            description: "简洁的IP地址查询工具，支持IPv4和IPv6。"
            logo: "images/favicons/ip.sb.ico"
      - name: "VPS与网络服务"
        links:
          - title: "RN-VPS"
            url: "https://my.racknerd.com/aff.php?aff=11799"
            description: "低价高速的VPS！"
          - title: "Vultr"
            url: "https://www.vultr.com/"
            description: "高性能云服务器，支持按小时计费。"
            logo: "images/favicons/Vultr.ico"
          - title: "Cloudflare"
            url: "https://www.cloudflare.com/"
            description: "提供CDN、DNS解析、域名托管等多种服务。"
      - name: "网络服务"
        links:
          - title: "ClouDNS"
            url: "https://www.cloudns.net/"
            description: "提供免费的DNS解析和域名管理服务。"
            logo: "images/favicons/ClouDNS.ico"
          - title: "USKG域名注册"
            url: "https://nic.us.kg/"
            description: "专业的域名注册和管理服务提供商。"
            logo: "images/favicons/USKG域名注册.ico"

  - name: "娱乐与生活"
    subcategories:
      - name: "影视音乐"
        links:
          - title: "花花吧影视"
            url: "https://huaweiba.live/"
            description: "免费的在线影视网站。"
          - title: "落雪音乐免费下载+免费音源"
            url: "https://www.123684.com/s/AJ3VVv-IrcBd"
            description: "免费开源的音乐软件，支持多平台。"
            logo: "images/favicons/落雪音乐免费下载+免费音源.ico"
      - name: "小游戏"
        links:
          - title: "4399小游戏"
            url: "https://www.4399.com/"
            description: "4399小游戏，休闲娱乐的最佳选择。"
            logo: "images/favicons/4399小游戏.ico"
          - title: "7K7K小游戏"
            url: "https://www.7k7k.com/"
            description: "7K7K小游戏，畅玩各类在线小游戏。"
            logo: "images/favicons/7K7K小游戏.png"
      - name: "小说与阅读"
        links:
          - title: "笔趣阁免费小鼠"
            url: "https://www.bqgui.cc/"
            description: "免费小说聚集地。"
            logo: "images/favicons/笔趣阁免费小鼠.ico"
          - title: "Project Gutenberg"
            url: "https://www.gutenberg.org/"
            description: "提供超过6万本免费电子书。"
            logo: "images/favicons/Project Gutenberg.ico"
      - name: "安卓实用工具"
        links:
          - title: "via浏览器"
            url: "https://viayoo.com/zh-cn/"
            description: "简洁支持广告屏蔽的浏览器。"
            logo: "images/favicons/via浏览器.ico"
          - title: "Obsidian笔记软件"
            url: "https://wwdx.lanzoue.com/b030yr97g"
            description: "免费多功能，可自定义云盘备份的笔记软件。"
            logo: "images/favicons/Obsidian笔记软件.ico"

  - name: "浏览器与美化"
    subcategories:
      - name: "浏览器扩展"
        links:
          - title: "uBlock Origin"
            url: "https://ublockorigin.com/"
            description: "高效、轻量级的广告拦截工具。"
            logo: "images/favicons/uBlock Origin.ico"
          - title: "Greasy Fork"
            url: "https://greasyfork.org/"
            description: "用户脚本分享平台，支持多种浏览器。"
            logo: "images/favicons/Greasy Fork.ico"
      - name: "浏览器美化"
        links:
          - title: "UserStyles"
            url: "https://userstyles.org/"
            description: "浏览器样式美化资源分享平台。"
          - title: "iTab 新标签页"
            url: "https://www.itab.link/"
            description: "简洁高效的新标签页工具，支持个性化定制。"
            logo: "images/favicons/iTab 新标签页.ico"

  - name: "反馈与联系"
    subcategories:
      - name: "联系作者"
        links:
          - title: "博客防丢失链接"
            url: "https://go.jianghu.cfd"
            description: "作者的博客网站。"
      - name: "问题反馈"
        links:
          - title: "问题反馈：看说明"
            url: "https://blog1.jianghu.cfd/talkback/"
            description: "想去催更，快去看看！（不要用代理进）。" 